apps/enroll/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r'^addcourse$', views.addcourse, name="addcourse"),
    url(r'^delete/(?P<id>\d+)', views.delete, name="delete")
   	

]

apps/form/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
	url(r"^$", views.index, name="index"),
	url(r'^surveys/process$', views.process),
	url(r'^result$', views.result)
]

apps/gold/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^process_money$", views.process, name="processmoney")

]

apps/ninjas/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r'^ninjas/(?P<color>\w+)$', views.show_color),
    url(r'^ninjas/$', views.four)
]

apps/registration/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^newuser$", views.newuser, name="newuser"),
    url(r"^login$", views.login, name="login"),
    url(r"^success$", views.success, name="success"),
    url(r"^usercourses$", views.usercourses, name="usercourses"),
    url(r'^delete/(?P<id>\d+)', views.delete, name="delete"),
    url(r'^addusertocourse$', views.addusertocourse, name="addusertocourse")
 
]

integrationproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^login/', include('apps.registration.urls', namespace = 'login')),
	url(r'^survey/', include('apps.form.urls', namespace = 'survey')),
	url(r'^ninjas/', include('apps.ninjas.urls', namespace= 'disappearing')),
	url(r'^ninja-gold/', include('apps.gold.urls', namespace ='ninjagold')),
	url(r'^courses/', include('apps.enroll.urls', namespace = 'courses'))
  ]

apps/enroll/models.py
from __future__ import unicode_literals

from django.db import models
from ..registration.models import User
# Create your models here.


class Course(models.Model):
	userlinks = models.ManyToManyField(User)
	name = models.CharField(max_length = 100)
	description = models.CharField(max_length = 100)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

apps/form/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/gold/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/ninjas/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/enroll/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Course
from ..registration.models import User
from django.core.urlresolvers import reverse

def index(request):
  
	
	context = {
	'courses': Course.objects.all(),
	
	}
	
	return render(request, 'enroll/index.html', context)

def addcourse(request):
	

	if request.method == 'POST':
		Course.objects.create(name = request.POST['name'], description = request.POST['description'])
	return redirect(reverse('courses:index'))

def delete(request, id):

	delcourse = Course.objects.get(id = id)
	
	context = {
    	'courses': delcourse
    }
	delcourse.delete()
	return redirect(reverse('courses:index'))

apps/form/views.py
from django.shortcuts import render, redirect, HttpResponse

def index(request):
	return render(request, 'form/index.html')
def process(request):
	request.session['name'] = request.POST['name']
	request.session['location'] = request.POST['location']
	request.session['language'] = request.POST['language']
	request.session['comments'] = request.POST['comments']
	if 'count' not in request.session:
		request.session['count'] = 1
	else:
		request.session['count'] +=1
	return redirect('/result')
def result(request):


	return render(request, 'form/result.html')

apps/gold/views.py
from django.shortcuts import render, redirect, HttpResponse
import random, datetime
from django.core.urlresolvers import reverse

def index(request):
	if 'gold' in request.session:
		return render(request, 'gold/index.html')
	else:
		request.session['gold'] = 0
		request.session['log'] = []
		return render(request, 'gold/index.html')

def process(request):
	if request.POST['building'] == "farm":
		randgold = random.randrange(1, 21)
		request.session['gold'] = request.session['gold'] + randgold
		request.session['log'].append('Earned ' + str(randgold) +  ' from the farm! ' + datetime.datetime.now().strftime('%Y-%m-%d %I:%M:%S %p'))
	

	elif request.POST['building'] == "cave":
		randgold = random.randrange(5, 11)
		request.session['gold'] = request.session['gold'] + randgold
		request.session['log'].append('Earned ' + str(randgold) +  ' from the cave!' + datetime.datetime.now().strftime('%Y-%m-%d %I:%M:%S %p'))
	
	elif request.POST['building'] == "house":
		randgold = random.randrange(2, 6)
		request.session['gold'] = request.session['gold'] + randgold
		request.session['log'].append('Earned ' + str(randgold) +  ' from the house!' + datetime.datetime.now().strftime('%Y-%m-%d %I:%M:%S %p'))


	elif request.POST['building'] == "casino":
		if random.random() <= .5:
			
			request.session['gold'] = request.session['gold'] + 50
			request.session['log'].append('Earned ' + str(50) +  ' from the casino!' + datetime.datetime.now().strftime('%Y-%m-%d %I:%M:%S %p'))
		else:
			request.session['gold'] = request.session['gold'] - 50
			request.session['log'].append('Lost ' + str(50) +  ' from the casino!' + datetime.datetime.now().strftime('%Y-%m-%d %I:%M:%S %p'))
	return redirect(reverse('ninjagold:index'))

apps/ninjas/views.py
from django.shortcuts import render, redirect, HttpResponse

def index(request):
	return render(request, 'ninjas/index.html')

def four(request):
	image = ['leonardo.jpg', 'raphael.jpg', 'donatello.jpg', 'michelangelo.jpg']
	context = {
	"image": image
	}

	return render(request, 'ninjas/ninja.html', context)

def show_color(request, color):
	image =  []
	context = {
	"image": image
	}
	if color == 'blue':
		image.append('leonardo.jpg')
	elif color == 'red':
		image.append('raphael.jpg')
	elif color == 'purple':
		image.append('donatello.jpg')
	elif color == 'orange':
		image.append('michelangelo.jpg')
	else:
		image.append('notapril.jpg')

	return render(request, 'ninjas/ninja.html', context)

apps/enroll/templates/enroll/destroy.html
<!DOCTYPE html>
<html lang='en'>
	<head>
		<meta charset="UTF-8">
		<title>Courses</title>
		 {% load staticfiles %}
		<link rel="stylesheet" href="{% static 'enroll/css/styles.css' %}" media="screen" title="no title"  charset="utf-8">
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	</head>
	<body>
		<div class="container">
			<h3>Are you sure you want to delete?</h3>
			
			<form action ='/delete/{{courses.id}}' method='post'>
				    	<input type="submit" value="Delete" class="btn btn-sm btn-danger">
				    	{% csrf_token %}
				    	</form>
				
		</div>

apps/enroll/templates/enroll/index.html
<!DOCTYPE html>
<html lang='en'>
	<head>
		<meta charset="UTF-8">
		<title>Courses</title>
		 {% load staticfiles %}
		<link rel="stylesheet" href="{% static 'enroll/css/styles.css' %}" media="screen" title="no title"  charset="utf-8">
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	</head>
	<body>
		<div class="container">
			<div class="form1">
				<form action="{% url 'courses:addcourse' %}" method='post'>
					{% csrf_token %}
					<label>Name:</label>

					<input type="text" name="name" class="form-control">
					<label>Description:</label>
					<textarea class="form-control" rows="3" name="description"></textarea>
					<input type="submit" value="Add Course" name="submit" class="btn btn-sm btn-info custombtn">
				</form>
			</div>
			<div class="content">
			
				 
			<table class="table table-hover table-bordered">
 				  <tr>
				    <th>Course</th>
				    <th>Description</th> 
				    <th>Created At</th>
				    <th>Remove</th>
				  </tr>
				  {% for course in courses %}
				  <tr>
				    <td>{{course.name}}</td>
				    <td>{{course.description}}</td> 
				    <td>{{course.created_at}}</td>
				    <td>
				    	<a href ="{% url 'courses:delete' id=course.id %}">Delete</a>
				   
				    </td>
  				  </tr>
 					 {% endfor %}
			</table>
				
			</div>
		</div>
	</body>

apps/form/templates/form/index.html
<html>
	<head>
		<meta charset="UTF-8">
		<title>Survey</title>
		  {% load staticfiles %}
		  <link rel="stylesheet" href="{% static 'form/css/form.css' %}" media="screen" title="no title"  charset="utf-8">
		    <!-- Latest compiled and minified CSS -->
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

			<!-- Optional theme -->
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

			<!-- Latest compiled and minified JavaScript -->
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	</head>
	<body>
		<div class="container">
			<div class="form">
				<form action = '/surveys/process' method = 'post'>
					First Name: <input type="text" name="name" class="form-control">
					  <br>
					  <select name="location" class="form-control">
					  <option value="Seattle">Seattle</option>
					  <option value="Chicago">Chicago</option>
					  <option value="Los Angeles">Los Angeles</option>
					  <option value="San Francisco">San Francisco</option>
					  </select>
					  <br>
					  <select name="language" class="form-control">
					  <option value="C++">C++</option>
					  <option value="Java">Java</option>
					  <option value="Python">Python</option>
					  <option value="Javascript">Javascript</option>
					  </select>
					  <br>
					  Comments:<textarea rows="3" width="500" name="comments" class="form-control">
					  </textarea>
					  <br>
					  <input type ='submit' value="submit" class='btn btn-sm btn-info'>
					  {% csrf_token %}
				</form>

			</div>
		</div>
	</body>
</html>

apps/form/templates/form/result.html
<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Survey</title>
		  {% load staticfiles %}
		  <link rel="stylesheet" href="{% static 'form/css/form.css' %}" media="screen" title="no title"  charset="utf-8">
					  <!-- Latest compiled and minified CSS -->
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

			<!-- Optional theme -->
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

			<!-- Latest compiled and minified JavaScript -->
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	</head>
	<body>
		<div class="container">
			<div id="submitted">
				<p>Thanks for submitting your information!!! You have submitted this form {{request.session.count}} times!
				</p>
			</div>
			<div class="form">
			<p>Name:	{{ request.session.name }}</p>
			<p>Location:{{ request.session.location}}</p>
			<p>Favorite Language:{{ request.session.language}}</p>
			<p>Comments:{{ request.session.comments}}</p>
			</div>
		</div>
	</body>
</html>

apps/gold/templates/gold/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Ninja Gold</title>
		  {% load staticfiles %}
		  <link rel="stylesheet" href="{% static 'gold/css/styles.css' %}" media="screen" title="no title"  charset="utf-8">
	</head>
    <body>
        <div class="container">
            
          
            Your Gold: 
             <div class="gold">
             {{ request.session.gold }}
            </div>
            <div class="action">
                <h2>Farm</h2>
                <h5>(Earn 20 Gold)</h5>
                <form action="{%url 'ninjagold:processmoney' %}" method='post'>
                {% csrf_token %}
                    <input type="hidden" value="farm" name="building">
                    <input type="submit" value="Find Gold!" class="btn btn-success">
                </form>
            </div>
            <div class="action">
                <h2>Cave</h2>  
                <h5>(Earn 5-10 Gold)</h5>
              <form action="{%url 'ninjagold:processmoney' %}" method='post'>
              {% csrf_token %}
                    <input type="hidden" value="cave" name="building">
                    <input type="submit" value="Find Gold!" class="btn btn-success">
                </form>
            </div>
            <div class="action">
                <h2>House</h2>
                <h5>(Earn 2-5 Gold)</h5>
                <form action="{%url 'ninjagold:processmoney' %}" method='post'>
                {% csrf_token %}
                    <input type="hidden" value="house" name="building">
                    <input type="submit" value="Find Gold!" class="btn btn-success">
                </form>
            </div>
            <div class="action">
                <h2>Casino</h2>
                <h5>(Earn/Lose 50 Gold)</h5>
                <form action="{%url 'ninjagold:processmoney' %}" method='post'>
                {% csrf_token %}
                    <input type="hidden" value="casino" name="building">
                    <input type="submit" value="Find Gold!" class="btn btn-success">
                </form>
            </div>
         
            <h4>Activities:</h4>
               <div class="activities">
               {% for i in request.session.log %}
               <p>{{ i }}</p>
               {%endfor%}
              </div>
        </div>
    </body>
</html>

apps/ninjas/templates/ninjas/index.html
<!DOCTYPE html>
<html>
	<head>
		<title>Disappearing Ninjas</title>
		<meta charset="UTF-8">
	</head>
	<body>
	No Ninjas Here
	</body>
</html>

apps/ninjas/templates/ninjas/ninja.html
<!DOCTYPE html>
<html>
	<head>
		<title>Disappearing Ninja</title>
		{% load staticfiles %}
    </head>
    <body>
      {% for x in image %}
      <p>
      <img src="{% static 'ninjas/img/'|add:x %}">
      </p>
      {% endfor %} 
    </body>
 </html>